Repository YevgenDemoTestOrganization/calculator-library, pull requests merged in 2023-11, with the labels that each got.

#12 BLZT-9 Add user 'Roman Novosad'
  pom.xml
Labels: size/XS

#15 [BLZT-11] Added developer to pom file
  pom.xml
Labels: size/XS

#14 [BLZT-10] add user Andrew Pikozh
  pom.xml
Labels: good first issue, size/XS

#21 Feature/2 test
  .github/workflows/maven.yml
  docker/README.md
  pom.xml
Labels: size/S
